FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    sudo \
    passwd \
    nano

WORKDIR /app

COPY user_manager.sh /app/user_manager.sh

RUN chmod +x /app/user_manager.sh

CMD ["/bin/bash"]